### ISSUE TITLE
Don't automatically refresh charts (they only update once per day)

### ISSUE THREAD

**Issue by robhudson** [mozilla/firefox-test-tube#156]
To see this happen, open the network monitor, then open a browser on an experiment page and wait. Every 1-2 minutes the API requests will repeat.

**Comment by openjck** [comment]
This is intended. The application re-fetches chart data on a regular interval (currently 60 seconds) just in case chart data has changed.

See the `refreshInterval` here:

https://github.com/mozilla/firefox-test-tube/blob/0d2ef488cbdb81a58ac540c2211a271196407666/src/components/containers/MetricContainer.js#L51-L53

**Comment by openjck** [comment]
Ah, it only updates every day. Right. In that case I think we can get rid of the `refreshInterval` altogether.

**Comment by openjck** [comment]
I also noticed that `refreshInterval` made Ensemble sluggish.
