### ISSUE TITLE
Switch from pyup to Renovate for Python dependencies if it's a suitable replacement

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#201]
Renovate can now open pull requests to update Python dependencies in addition to NPM dependencies. See #198 as one example.

If Renovate is a suitable replacement for pyup, we should disable pyup and use Renovate instead so that we have one less service to manage. I'll let @robhudson do that assessment.

**Comment by robhudson** [comment]
We decided to keep pyup for now. See 2d5d0c0395cade5ba40711ccf4f91f40e365d94c
