### ISSUE TITLE
Remove Firefox histograms

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/firefox-test-tube#206]
Since we are moving experiment analysis into a workflow that involves batch jobs that are visualized in Iodide when an experiment completes, and focusing Test Tube on 'operational' experiment health, we should remove the histograms that appear in Test Tube so that they do not create the impression that Test Tube can be used to evaluate things like engagement, search, etc.

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
