### ISSUE TITLE
If there are less than 20 buckets for a metric, show a bar graph instead of a line graph

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#21]

**Comment by openjck** [comment]
@robhudson I'm still not great with some of the terminology. What is a bucket, exactly? Essentially one x/y pair or something else?

**Comment by spasovski** [comment]
Set of x-values for us by the time it ends up in the JSON response.

**Comment by openjck** [comment]
Gotcha. So `data.length` essentially.
