### ISSUE TITLE
make shell: docker-compose run server bash failure

### ISSUE THREAD

**Issue by spasovski** [mozilla/firefox-test-tube#217]
Locally I get:

spasovski:~/projects/test-tube (master):: make shell
docker-compose run -u 502:20 server bash
Starting test-tube_db_1 ... done
I have no name!@7c07f1d6b6eb:/app$ 
I have no name!@7c07f1d6b6eb:/app$ pg_restore -h db -U postgres -d postgres --clean latest.dump
Use of uninitialized value $gid in getgrgid at /usr/share/perl5/PgCommon.pm line 783.
pg_restore: [archiver] unsupported version (1.13) in file header

**Comment by robhudson** [comment]
The solution is to not use the Makefile which adds the local user, which is needed for Python code to run, like when creating Django migrations.

I updated the documentation for database imports to explicitly show the `docker-compose` way of getting a shell.
