### ISSUE TITLE
Import mean stats for retention metrics

### ISSUE THREAD

**Issue by jklukas** [mozilla/firefox-test-tube#223]
https://github.com/mozilla/telemetry-batch-view/pull/453 will be merged in a moment, and adds the following retention metrics:

```
retained_in_week_1
retained_in_week_2
retained_in_week_3
retained_active_in_week_1
retained_active_in_week_2
retained_active_in_week_3
```

It also populates `confidence_level` values for both retention and engagement metrics, and it adds a Mean statistic for those measurements.

The new retention metrics are mostly already accommodated by https://github.com/mozilla/firefox-test-tube/pull/213 but we'll want to show the mean for these rather than the median. The underlying values are basically boolean (either 0.0 or 1.0), so percentiles are all 0 or 1 as well. The mean essentially communicates the fraction of retained users for the given week.

We probably want to check whether the metric name starts with `retained_` and use mean rather than median if that's the case.

**Comment by openjck** [comment]
@robhudson Is this still something we might want to do?

**Comment by robhudson** [comment]
I believe the upstream stats have or will be going away. Closing this.
