### ISSUE TITLE
Include experiments with real-time data in the experiments list API

### ISSUE THREAD

**Issue by robhudson** [mozilla/firefox-test-tube#232]
If the experiment hasn't been imported yet we have minimal data (like full name or creation date) but we can include it here so users can navigate to the experiment detail page.

**Comment by gregglind** [comment]
A+.   I wanted this yesterday!  

Use case:  during the first second of deploy, as a Shield Sheriff, I wait for the "liveness email" that Mreid / Hindsight sends out.  That's how I verify that the thing was adopted by (at least 1) client.  Maybe this same email could trigger the 'setup the experiment dashboard' job.

(As a stretch:  "any data  today / last reported data" are valuable Operational signals.

Thanks for anticipating this. I  would literally use this today.

**Comment by robhudson** [comment]
For the front-end we will include a "real-time" flag so the front-end can display the charts on the detail page differently knowing that the data from the nightly import is not available.

**Comment by robhudson** [comment]
We are re-opening this and backing out the existing code because it is not ideal. The filtering of experiments still includes experiments that are disabled when checking them in the normandy API.

To that end the better approach would be to get the list of active experiments in the normandy API before including them in the experiments list API that the front-end uses to display the list of experiments. The current code will be backed out right away and the new code will be worked on.

One workaround is that the link in Experimenter titled "Live Monitoring Dashboard" will take you to an experiment and show you the real time data.
