### ISSUE TITLE
Add axis labels to population and enrollment graphs

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/firefox-test-tube#235]
We need to add axis labels to all the population and enrollment graphs, right now there's no indication of what they're measuring.

**Comment by rafrombrc** [comment]
The x-axis values are dates, which are quite clear, but we can add 'clients' as a y-axis label.

**Comment by spasovski** [comment]
Addressed with: https://github.com/mozilla/firefox-test-tube/commit/343d03e
