### ISSUE TITLE
Population graph should always start at 0

### ISSUE THREAD

**Issue by jaredkerim** [mozilla/firefox-test-tube#236]
It looks like a lot of the population graphs start at some non zero population size, ideally these should all start at 0 so you can see them from the start.  I'm not sure this is whether we don't know the 'true' start of the experiment or because that's when the data started being available.  Perhaps integration with the Experimenter API can help get 'true' start dates?

**Comment by rafrombrc** [comment]
For expedience we'll just cheat and prepend a 0 value at FirstDataDate - 1, but we might hit experimenter for the actual start date down the road.
