### ISSUE TITLE
Link to recipe in Delivery Console or Normandy API

### ISSUE THREAD

**Issue by mythmon** [mozilla/firefox-test-tube#237]
It would be handy to have a link to the Delivery Console page for a given recipe. For example [this Test Tube page](https://firefox-test-tube.herokuapp.com/experiments/prefflip-simplified-onboarding-overlay-v1-0-1473580/) corresponds with [this Delivery Console page](https://delivery-console.prod.mozaws.net/recipe/528/).

The Delivery Console urls use the recipe ID, which is the primary key used in the Normandy API, if you're already using that.

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
