### ISSUE TITLE
Add enrollment/unenrollment summary counts near top with Clients and Pings

### ISSUE THREAD

**Issue by jtg567** [mozilla/firefox-test-tube#238]
Seeing the counts and ratios of enrolled vs. unenrolled for each study can be instantly diagnostic of enrollment issues, which ideally we can catch right away.

Having those broken out by branches and Total to match the Clients and Pings counts on top would conform to the existing format and summarize the enrollment time series charts in a way that's consistent with the Clients count and Populations time series together.

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
