### ISSUE TITLE
Ensure consistent color mappings per branch across plots

### ISSUE THREAD

**Issue by jtg567** [mozilla/firefox-test-tube#244]
Glancing at https://firefox-test-tube.herokuapp.com/experiments/Default_Browser_Pref-Flip/ today, I noted Control was red in the Populations time series but inverted to blue in the enrollment charts (and vice-versa for the Prompt branch).

**Comment by spasovski** [comment]
Great catch. Thanks for filing.

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
