### ISSUE TITLE
Return experiment slug from API

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#25]
Human-readable names are not available for all experiments. In these cases, the front-end can fall back to using the slug from the */experiments/* endpoint instead if one is provided.

**Comment by robhudson** [comment]
My proposal:

1. Let's add a `slug` to the data returned from the experiments endpoint.
2. The front-end can handle the fallback if `name` is null.

**Comment by openjck** [comment]
Sounds good to me. The front-end is actually already doing that fallback expecting `slug` to be there.
