### ISSUE TITLE
Standardize Y-axis ranges among charts in same domain

### ISSUE THREAD

**Issue by jtg567** [mozilla/firefox-test-tube#254]
[Noticed from this screenshot](https://screenshots.firefox.com/6PLfHQqlcYcGLvjq/firefox-test-tube-staging.herokuapp.com) that the Y max for Enrollments is 3000 vs 20 for Unenrollments.

Matching the scales between plots makes them instantly visually comparable without additional and expensive cognitive operations to scale mentally.

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
