### ISSUE TITLE
Experiment Population Graphs Broken

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/firefox-test-tube#388]
I was wondering what was up with some missing data in the population graphs for experiments and looking at the import script and the population data still seems to depend on the aggregates job which no longer runs. There are also quite a few recent, live pref flip experiments that aren't on the list at all either but the data appears to be in the db, based on some futzing around on grafana.

**Comment by robhudson** [comment]
The current import script is pulling population data from the experiments dataset, not experiment aggregates. Can you point at what specifically in the import script looks like it depends on the aggregates job?

**Comment by robhudson** [comment]
Also can you share which experiment IDs you're seeing in the db and not on the website? I can try to confirm and investigate.

**Comment by sunahsuh** [comment]
Oh duh 😅

I realized what happening with the missing population graphs : they're marked as high population. If we want to fix this one option would be to do one query across clients_daily that explodes the `experiments` keys and does a groupBy count on them.

Re: missing experiments:
https://experimenter.services.mozilla.com/experiments/search-volume-in-private-browsing-observational-study/
https://experimenter.services.mozilla.com/experiments/pref-flip-defaultoncookierestrictions-1506704/

**Comment by openjck** [comment]
This should no longer be needed now that the front-end has been removed. Please reopen if I'm mistaken.
