### ISSUE TITLE
Create enroll-failed/unenroll-failed fields to test tube enrollments model/api

### ISSUE THREAD

**Issue by sunahsuh** [mozilla/firefox-test-tube#391]
Just had a meeting with @jaredkerim where we realized we're not collecting this in the test tube enrollments job. We should add those fields in the api, and then we can make sure the streaming job aggregates and posts them to the backend (will post a link here to the streaming job bug after I file that)

**Comment by sunahsuh** [comment]
The streaming job bug that depends on this issue is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1536232

**Comment by sunahsuh** [comment]
I also found a few other event types of interest, so the list of new rollup fields is expanded to:
graduate_count
update_count
enroll_failed_count
unenroll_failed_count
update_failed_count

**Comment by openjck** [comment]
@robhudson Is this still something we might want to do, given the recent changes?

**Comment by robhudson** [comment]
Reopening until this is pushed all the way to production.

**Comment by robhudson** [comment]
This has now been merged and pushed to staging and production.
