### ISSUE TITLE
Disable keybindings for navigating paginator

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#46]
Rob found this weird little "feature."

## Steps to reproduce

1. Click the **next* link of any paginator
2. Hit any key

After hitting any key, the paginator will move next again. The same works in reverse if you hit the previous button in step 1.

These should be disabled because they can get in the way of using CTRL+F and other useful shortcuts. react-paginate might be doing this, but they don't appear to document the feature.

**Comment by rafrombrc** [comment]
Closing bc we're not likely to need pagination going forward.
