### ISSUE TITLE
Pull metric metadata from probe dictionary during import

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/firefox-test-tube#50]
Georg's probe dictionary (https://georgf.github.io/fx-data-explorer/) has come along very nicely, with descriptions of the probes. IIUC the dictionary is populated by a single JSON structure.The import job should be updated to pull down this JSON and add metric descriptions to the database.

**Comment by openjck** [comment]
@robhudson Is this still something we might want to do, given the recent changes?

**Comment by robhudson** [comment]
Closing, but if we want this in the future we can re-open.
