### ISSUE TITLE
Auto-refresh fails on some pages

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#53]
## Steps to reproduce

1. Open a page with a bar chart
2. Wait for the charts on the page to refresh (currently 60 seconds)

## Result

The screen goes white and an error is printed to the console.

**Comment by openjck** [comment]
This also fails on [this page](https://firefox-test-tube.herokuapp.com/experiments/569/) which doesn't appear to have any bar charts. (Although one chart has no data; maybe that's the bar chart?)

**Comment by spasovski** [comment]
https://github.com/mozilla/firefox-test-tube/pull/103 fixes this
