### ISSUE TITLE
Provide auth0 creds for local development

### ISSUE THREAD

**Issue by robhudson** [mozilla/firefox-test-tube#56]
We we added the login required setting on the index page and added mozilla-django-oidc we blocked easy local development. We should fix this.

**Comment by openjck** [comment]
I thought we already had a solution for this. I haven't noticed any issues locally. We pushed authentication to prod recently but oauth has been enabled on master for a long time.

**Comment by robhudson** [comment]
This has been done. The file `backend.env.dist` has been added as a template for the credentials. It was advised not to share the secret key publicly so any new developers will either need to get their own auth0 credentials or ask for a copy.
