### ISSUE TITLE
use slugs instead of IDs for experiment URLs

### ISSUE THREAD

**Issue by spasovski** [mozilla/firefox-test-tube#78]
Main goal being that we can predict what an experiment's TT URL will be.

**Comment by openjck** [comment]
Note to selves:

[slugify](https://www.npmjs.com/package/slugify) might help with this.

**Comment by robhudson** [comment]
Both the slug and the id are in the `/v2/experiments/` API endpoint.

**Comment by robhudson** [comment]
@spasovski I think we've completed this, right?
