### ISSUE TITLE
Expose authors in API

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#80]
Currently, the output of the */experiments/[eid]* output ([example](https://firefox-test-tube.herokuapp.com/v2/experiments/2240/)) includes an empty array for the `authors` property. Is this something we can get from upstream and make available in the API, @robhudson? We already have front-end support for it.

**Comment by openjck** [comment]
Here's an example of what the front-end expects:

https://github.com/openjck/firefox-test-tube-mock-api/blob/master/api.json#L3196-L3209

**Comment by robhudson** [comment]
The [Normandy API](https://normandy.services.mozilla.com/api/v1/recipe/?latest_revision__action=3&status=enabled) only has the email (not names), but it also has extra context (creator vs approver). So we may want to tweak what we display slightly?

**Comment by openjck** [comment]
That works for me. Can you point me to more specifics about what Normandy has? Does it have one email from a creator and one email for an approver or is it more complex than that?

**Comment by robhudson** [comment]
If you click the link I shared you'll see exactly what's in the API. But yes, just one email it looks like.

**Comment by openjck** [comment]
This is no longer needed now that the front-end has been removed.
