### ISSUE TITLE
Expose experiment descriptions in API

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#81]
Is this something we can get from upstream, @robhudson? We already support showing this in the front-end.

Here's an example of what the front-end expects:

https://github.com/openjck/firefox-test-tube-mock-api/blob/master/api.json#L3195

**Comment by robhudson** [comment]
The [Normandy API](https://normandy.services.mozilla.com/api/v1/recipe/?latest_revision__action=3&status=enabled) does not contain a description.

**Comment by openjck** [comment]
Gotcha. I'm tempted to say we should encourage Normandy to add one (and people to write them) but honestly, I never wrote descriptions in Optimizely. Maybe they're not that useful after all.

I'd be happy to remove descriptions support in the front-end if you think it would make sense to also remove the empty descriptions from the API.

**Comment by robhudson** [comment]
This may be something we eventually get from Experimenter? So I wouldn't completely forget about it but we have no way of gathering this at the moment that I see.

**Comment by rafrombrc** [comment]
Experimenter will capture descriptions, and I presume the Experimenter API will provide them, but for now I'd like to not worry about exposing this in Test Tube and reclaiming the screen real estate.

**Comment by openjck** [comment]
This is no longer needed now that the front-end has been removed.
