### ISSUE TITLE
Expose chart descriptions in API

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#82]
Is this something we can get from upstream, @robhudson? We already support showing this in the front-end.

Here's an example of what the front-end expects:

https://github.com/openjck/firefox-test-tube-mock-api/blob/master/api.json#L112

**Comment by robhudson** [comment]
I think there was a thought that we can get this from George's probe dictionary?

**Comment by spasovski** [comment]
duplicate

**Comment by openjck** [comment]
I don't think this is a duplicate, is it? #82 is for experiment descriptions.

**Comment by spasovski** [comment]
Indeed I misread thanks. Granted I don't know how useful these would be in the long run but that's not up to us.

**Comment by openjck** [comment]
This is no longer needed now that the front-end has been removed.
