### ISSUE TITLE
Link from chart titles to the corresponding pages in the probe dictionary

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#83]

**Comment by spasovski** [comment]
The reverse mapping is here: https://github.com/mozilla/probe-dictionary/blob/master/explore.js#L547

**Comment by spasovski** [comment]
Also see: https://github.com/mozilla/telemetry-dashboard/blob/gh-pages/new-pipeline/src/dashboards.js#L1050

**Comment by rafrombrc** [comment]
Closing bc we might not have any direct probe metrics in these dashboards anyway.
