### ISSUE TITLE
Indicate which charts have statistically significant differences between summary statistics with a high confidence interval

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#85]
We'll get this information from the API. Optimizely's visual treatment of statistical significance is good prior-art for this.

**Comment by robhudson** [comment]
Can you share a screenshot of what this looks like? I'd be interested in seeing it.

**Comment by openjck** [comment]
Here are a couple of screenshots from Optimizely. I'm not saying we should follow this layout exactly, or anything close to it necessarily, just that I like the way they highlight the "winner" very clearly.

![](https://user-images.githubusercontent.com/933396/35595033-51363fd4-05e3-11e8-90bc-0155be62f802.png)

![optimizely-turn-data-into-action](https://user-images.githubusercontent.com/933396/35595045-595c9b40-05e3-11e8-8764-3c0e365d0f53.jpg)

**Comment by rafrombrc** [comment]
Closing this bc this will land on the analysis side of the experimentation tooling, Test Tube will focus on monitoring.
