### ISSUE TITLE
Hitting the "Show outliers" button sometimes causes the app to crash

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#94]
## Steps to reproduce

1. Visit [this page](https://firefox-test-tube.herokuapp.com/experiments/46/?page=5)
2. Click *Show outliers*

## Result

The page goes white and an error is printed to console. It's unclear if this will still happen after #92 lands.

**Comment by rafrombrc** [comment]
Closing bc this only happened on a specific experiment, and will likely not be an issue when we stop showing all of the probe metrics.
