### ISSUE TITLE
Some pages are too wide

### ISSUE THREAD

**Issue by openjck** [mozilla/firefox-test-tube#96]
## Steps to reproduce

1. Visit [this page](https://firefox-test-tube.herokuapp.com/experiments/569/) or any other page that has charts with many populations.

## Result

The page is too wide, not centered, and a horizontal scrollbar appears. I don't want to show a true screenshot here to preserve the secrecy of the data, but it looks something like this:

![](https://user-images.githubusercontent.com/933396/36167764-f63e6ef2-10c4-11e8-9175-6dd2b0cc1bc7.png)

**Comment by spasovski** [comment]
https://github.com/mozilla/firefox-test-tube/pull/102 should address this.
